# Generated by Django 2.2.6 on 2020-03-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200307_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
