# Generated by Django 2.2.6 on 2020-03-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_company_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tribalyouth',
            old_name='fullname',
            new_name='lastname',
        ),
    ]
