# Generated by Django 2.2.6 on 2020-03-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200308_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribalyouth',
            name='image',
            field=models.ImageField(default='media/accounts/images/admin.png', upload_to='media/accounts/images'),
        ),
    ]
