# Generated by Django 2.2.6 on 2020-03-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribalyouth',
            name='about_you',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='tribalyouth',
            name='area',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tribalyouth',
            name='city_pincode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tribalyouth',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tribalyouth',
            name='experience',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tribalyouth',
            name='father_mobile_no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='tribalyouth',
            name='father_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tribalyouth',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='tribalyouth',
            name='language',
            field=models.CharField(default='hindi', max_length=50),
        ),
        migrations.AddField(
            model_name='tribalyouth',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tribalyouth',
            name='talent_category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tribalyouth',
            name='talent_description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='tribalyouth',
            name='talent_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tribalyouth',
            name='your_mobile_no',
            field=models.CharField(default='', max_length=10),
        ),
    ]
