# Generated by Django 2.2.6 on 2020-03-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200321_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribalyouth',
            name='experience',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
