# Generated by Django 2.2.6 on 2020-03-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200323_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_desc',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='no_of_employee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
