# Generated by Django 2.2.6 on 2020-03-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20200327_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribalyouth',
            name='cover_photo',
            field=models.ImageField(default='', upload_to='cover_photo'),
        ),
    ]
