# Generated by Django 2.2.6 on 2020-07-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20200413_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribalyouth',
            name='website',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='tribalyouth',
            name='your_mobile_no',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
