# Generated by Django 2.2.6 on 2020-06-19 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent_images', '0005_auto_20200619_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimages',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
