# Generated by Django 2.2.6 on 2020-03-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200321_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribalyouth',
            name='experience',
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
