# Generated by Django 2.2.6 on 2020-03-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200321_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribalyouth',
            name='experience',
            field=models.CharField(default='Fresher', max_length=10),
        ),
    ]
