# Generated by Django 2.2.6 on 2020-03-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200321_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribalyouth',
            name='experience',
            field=models.CharField(max_length=20),
        ),
    ]
