# Generated by Django 2.2.6 on 2020-03-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200323_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='images',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
