# Generated by Django 2.2.6 on 2020-03-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200323_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='images',
            field=models.ImageField(default='', null=True, upload_to='company_user'),
        ),
    ]
