# Generated by Django 2.2.6 on 2020-03-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20200324_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='class_of_company',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='images',
            field=models.ImageField(default='media/admin.png', null=True, upload_to='company_user'),
        ),
    ]
