# Generated by Django 2.2.6 on 2020-03-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20200327_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='fax_no',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='landline_no',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
