# Generated by Django 2.2.6 on 2020-03-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20200327_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribalyouth',
            name='about_you',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tribalyouth',
            name='father_mobile_no',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tribalyouth',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tribalyouth',
            name='talent_description',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
