# Generated by Django 2.2.6 on 2020-04-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20200331_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cover_photo',
            field=models.ImageField(blank=True, default='media/cover_photo/subscribe-bg.png', null=True, upload_to='cover_photo'),
        ),
    ]
