# Generated by Django 2.2.6 on 2020-08-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20200707_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribalyouth',
            name='date_joined',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
