# Generated by Django 2.2.6 on 2020-08-06 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_tribalyouth_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tribalyouth',
            old_name='date_joined',
            new_name='join_date',
        ),
    ]
