# Generated by Django 2.2.6 on 2020-06-20 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent_images', '0006_auto_20200619_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimages',
            name='title',
            field=models.CharField(default=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=100),
        ),
    ]
