# Generated by Django 2.2.6 on 2020-06-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_images', '0007_userimages_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimages',
            name='desc',
            field=models.TextField(default='###########'),
        ),
        migrations.AlterField(
            model_name='userimages',
            name='title',
            field=models.CharField(default='Image :', max_length=100),
        ),
    ]
